### ISSUE TITLE
unhuman-like behavior for drawing situation

### ISSUE THREAD

**Issue by khoramshahi** [supertorpe/chessendgametraining#24]
when a position is draw the computer (table or stockfish) would not try to resist and create problems for the winning side which makes the game less educational.

**Comment by supertorpe** [comment]
Yes, this is a known problem and has no general solution. For example, when stockfish knows that it will receive mate, it tries to receive the longest sequence of mate (thinking that the opponent is not going to make any mistakes), instead of trying to create difficulties for the opponent to make a mistake. Not even setting contempt values can improve this behavior.

**Comment by khoramshahi** [comment]
I think the solution to this is to include variations, and have prepared computer answers for the human move. But I think this will also complicate everything.

I am not a app developer, but if I get a bit of time and will look into it.
I was also thinking of a "space-repetition" feature as well that makes sure that learner remember the solution and it was not just out of luck.

**Comment by supertorpe** [comment]
Manually preparing responses to variants of each position would be outside the scope of the project.
Spaced repetition is a good idea that could be studied in another issue. I proceed to close this one.

**Comment by gr-g** [comment]
Hello, I write in this issue from years ago because I think that nowadays there are some reasonable options available to improve the move selection algorithm, that perhaps can be considered.

One simple idea, for checkmate positions, could be to select the best move for the computer side from the tablebase according to the distance-to-zero metric (dtz), instead of distance-to-mate (dtm). (dtz should be available from the lichess API together with dtm). In this way, the computer selects the move that delays pawn promotions as much as possible. This makes the computer more combative compared to maximizing dtm, which typically (in KPvK and similar) results in the defending king running away from the pawn trying to promote, making the puzzle pointless.
I think (not 100% sure) that this is the approach used by this app: https://app.endgametrainer.com/. While not perfect, subjectively it seems to produce better results.

Another idea, more invasive, would be to replace stockfish with the [Maia](https://www.maiachess.com/) "human-like" engine. Maia gives a probability distribution on potential moves reflecting how much a move is likely to be played by a human (with selectable skill). Together with a tablebase query to restrict the choice only among the "correct" moves, picking the most human move from the Maia engine would most probably give a good result for both draw and checkmate positions. Selecting a random move according to the Maia distribution could also make a lot of sense, to introduce variety in the computer play and ensuring that the player learns how to react to different defending approaches.

Some links for reference:
https://github.com/CSSLab/maia2
https://github.com/CSSLab/maia-platform-frontend
https://lichess.org/@/HollowLeaf/blog/integrating-maia2-the-human-like-chess-engine-into-my-chess-application/zi3EhDn5

**Comment by supertorpe** [comment]
@gr-g  thanks for your suggestions.

https://chess-endgame-trainer.mooo.com/fen/8/6k1/6P1/8/6PK/8/8/8%20w%20-%20-%200%201

If you move Kh5, most of the time, the black king started an escape to the center of the board (Kf6, Ke5...) looking to lose with the longest mate sequence (trivial win for white). 

This was "fixed" in v3.0.25, but maybe it's worth exploring your ideas.

**Comment by gr-g** [comment]
Thanks for the feedback!

Here is a link where you can play the same position against Maia: https://www.maiachess.com/play/maia?playType=againstMaia&player=white&maiaVersion=maia_kdd_2600&timeControl=10%2B0&isBrain=false&sampleMoves=true&simulateMaiaTime=false&startFen=8%2F6k1%2F6P1%2F8%2F6PK%2F8%2F8%2F8+w+-+-+0+1&returnTo=&challengeId=&forcedColor=&modalTitle=&modalSubtitle=

The computer moves have definitely a more natural feel.
